#!/bin/bash

# Script para ejecutar en tu entorno local o servidor con acceso a MongoDB

URLDB='mongodb+srv://cerramaximiliano:hYN46M8PuHFl0oDa@cluster0.t9oxary.mongodb.net/law_analytics?retryWrites=true&w=majority'

echo "=================================================="
echo "EJECUTAR ESTOS COMANDOS EN TU MÁQUINA LOCAL"
echo "=================================================="
echo ""
echo "# 1. Clonar o ir al repositorio:"
echo "cd /ruta/a/la-subscriptions"
echo ""
echo "# 2. Instalar dependencias (si es necesario):"
echo "npm install"
echo ""
echo "# 3. Ejecutar diagnóstico del usuario:"
echo "export URLDB='$URLDB'"
echo "node scripts/diagnoseEmailIssue.js maximilian@rumba-dev.com"
echo ""
echo "# 4. Ver qué cambios necesitan los templates (DRY RUN):"
echo "node scripts/fixTemplateVariables.js --dry-run"
echo ""
echo "# 5. Aplicar correcciones de templates:"
echo "node scripts/fixTemplateVariables.js --apply"
echo ""
echo "=================================================="
echo ""
echo "O USAR MONGODB COMPASS:"
echo "=================================================="
echo ""
echo "1. Abrir MongoDB Compass"
echo "2. Conectar con: $URLDB"
echo "3. En el Shell, cargar: load('scripts/mongoDBDiagnosis.js')"
echo ""
echo "O ejecutar manualmente estas consultas:"
echo ""
echo "const user = db.users.findOne({ email: 'maximilian@rumba-dev.com' })"
echo "const userId = user._id"
echo "print('Usuario:', user.email, 'ID:', userId)"
echo ""
echo "const folders = db.folders.countDocuments({ userId: userId, archived: { \$ne: true } })"
echo "const calculators = db.calculators.countDocuments({ userId: userId, archived: { \$ne: true } })"
echo "const contacts = db.contacts.countDocuments({ userId: userId, archived: { \$ne: true } })"
echo ""
echo "print('Carpetas activas:', folders)"
echo "print('Calculadoras activas:', calculators)"
echo "print('Contactos activos:', contacts)"
echo ""
echo "const foldersToArchive = Math.max(0, folders - 5)"
echo "const calculatorsToArchive = Math.max(0, calculators - 3)"
echo "const contactsToArchive = Math.max(0, contacts - 10)"
echo ""
echo "print('Carpetas a archivar:', foldersToArchive)"
echo "print('Calculadoras a archivar:', calculatorsToArchive)"
echo "print('Contactos a archivar:', contactsToArchive)"
echo ""
echo "const hasExcess = foldersToArchive > 0 || calculatorsToArchive > 0 || contactsToArchive > 0"
echo "print('Excede límites:', hasExcess ? 'SÍ' : 'NO')"
echo "print('Template correcto:', hasExcess ? 'gracePeriodReminderWithExcess' : 'gracePeriodReminderNoExcess')"
echo ""
